name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  composer-normalize:
    name: "composer-normalize"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Run composer normalize"
        uses: "docker://localheinz/composer-normalize-action:0.5.2"

  prettier:
    name: "Prettify markdown"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          ref: "${{ github.head_ref }}"

      - name: "Prettify markdown"
        uses: "creyD/prettier_action@v3.2"
        with:
          prettier_options: '--write --tab-width=2 **/*.md'
          commit_message: "Prettify markdown"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  static-code-analysis:
    name: "Static Code Analysis"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          php-version: "${{ env.PHP_VERSION }}"

      - name: "Install dependencies with composer"
        run: "composer install"

      - name: "Run phpstan/phpstan"
        run: "composer stan"

  tests:
    name: "Tests"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          php-version: "${{ env.PHP_VERSION }}"

      - name: "Install dependencies with composer"
        run: "composer install"

      - name: "Set up the database"
        run: |
          sudo systemctl start mysql.service
          mysql --user=root --password=root --execute='CREATE DATABASE laravel;'
      - name: "Run tests with phpunit/phpunit"
        run: "composer test"

